import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Input from "../components/input";
import Layout from "../components/layout";
import {
  TrashIcon,
  PencilIcon,
  PlusCircleIcon,
} from "@heroicons/react/24/outline";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Contacts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div>
          <div className="py-6">
            <div className="flex justify-between mx-auto max-w-7xl px-4 sm:px-6 md:px-8">
              <h1 className="text-2xl font-semibold text-gray-900">Contacts</h1>
              <button className="bg-ctBlue-500 p-2 hover:bg-ctBlue-600 text-white hover:bg-opacity-[0.8] gap-2 inline-flex flex-wrap items-center justify-center rounded-[4px] dark:border-ctBlue-500">
                <PlusCircleIcon className="h-6 w-6" aria-hidden="true" />
                Add Contact
              </button>
            </div>
            <div className="mx-auto max-w-7xl px-4 sm:px-6 md:px-8">
              <div className="py-4">
                <div className="grid grid-cols-1 gap-6 mb-6 lg:grid-cols-3">
                  <div className="w-full px-4 py-5 bg-white rounded-lg shadow">
                    <div className="text-sm font-medium text-gray-500 truncate">
                      Total users
                    </div>
                    <div className="mt-1 text-3xl font-semibold text-gray-900">
                      12,00
                    </div>
                    <div className="flex justify-end gap-4">
                      <button className="hover:text-green-700">
                        <PencilIcon className="h-6 w-6" aria-hidden="true" />
                      </button>
                      <button className="hover:text-red-600">
                        <TrashIcon className="h-6 w-6" aria-hidden="true" />
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
}
